[project]
name = "client"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "flatbuffers>=24.12.23",
    "zmq>=0.0.0",
]
